### ISSUE TITLE
Troubles after install, help needed

### ISSUE THREAD

**Issue by DuyguA** [cmusatyalab/openface#104]
I recently installed Torch and Openface but it seems that nothing works. I'm on Ubuntu 14.04 with Torch 7.

```
duygualtinok@duygualtinok:~/openface$ ./run-tests.sh 
/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
tests.openface_api_tests.test_pipeline ... ERROR
tests.openface_batch_represent_tests.test_batch_represent ... FAIL
tests.openface_demo_tests.test_compare_demo ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... FAIL
tests.openface_neural_net_training_tests.test_dnn_training ... FAIL

======================================================================
ERROR: tests.openface_api_tests.test_pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_api_tests.py", line 64, in test_pipeline
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)duygualtinok@duygualtinok:~/openface$ ./run-tests.sh 
/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
tests.openface_api_tests.test_pipeline ... ERROR
tests.openface_batch_represent_tests.test_batch_represent ... FAIL
tests.openface_demo_tests.test_compare_demo ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... FAIL
tests.openface_neural_net_training_tests.test_dnn_training ... FAIL

======================================================================
ERROR: tests.openface_api_tests.test_pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_api_tests.py", line 64, in test_pipeline
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 


======================================================================
FAIL: tests.openface_batch_represent_tests.test_batch_represent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_batch_represent_tests.py", line 38, in test_batch_represent
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_demo_tests.test_compare_demo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 38, in test_compare_demo
    assert "0.763" in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
Traceback (most recent call last):
  File "/home/duygualtinok/openface/demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "/home/duygualtinok/openface/demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 



--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 51, in test_classification_demo_pretrained
    assert "Predict SteveCarell with 0.97 confidence." in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
Traceback (most recent call last):
  File "/home/duygualtinok/openface/demos/classifier.py", line 175, in <module>
    infer(args)
  File "/home/duygualtinok/openface/demos/classifier.py", line 105, in infer
    rep = getRep(img).reshape(1, -1)
  File "/home/duygualtinok/openface/demos/classifier.py", line 77, in getRep
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 



--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 55, in test_classification_demo_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_neural_net_training_tests.test_dnn_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_neural_net_training_tests.py", line 36, in test_dnn_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

----------------------------------------------------------------------
Ran 6 tests in 6.303s

FAILED (errors=1, failures=5)

  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 


======================================================================
FAIL: tests.openface_batch_represent_tests.test_batch_represent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_batch_represent_tests.py", line 38, in test_batch_represent
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_demo_tests.test_compare_demo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 38, in test_compare_demo
    assert "0.763" in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
Traceback (most recent call last):
  File "/home/duygualtinok/openface/demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "/home/duygualtinok/openface/demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 



--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 51, in test_classification_demo_pretrained
    assert "Predict SteveCarell with 0.97 confidence." in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    /home/duygualtinok/openface/openface/openface_server.lua:19: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
Traceback (most recent call last):
  File "/home/duygualtinok/openface/demos/classifier.py", line 175, in <module>
    infer(args)
  File "/home/duygualtinok/openface/demos/classifier.py", line 105, in infer
    rep = getRep(img).reshape(1, -1)
  File "/home/duygualtinok/openface/demos/classifier.py", line 77, in getRep
    rep = net.forward(alignedFace)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 150, in forward
    rep = self.forwardPath(t)
  File "/home/duygualtinok/openface/openface/torch_neural_net.py", line 107, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.
+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.
  If this gives illegal instruction errors, see the section on
  this in our FAQ at http://cmusatyalab.github.io/openface/faq/
+ See this GitHub issue if you are running on
  a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42
+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/duygualtinok/openface/openface/openface_server.lua', '-model', '/home/duygualtinok/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 



--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_demo_tests.py", line 55, in test_classification_demo_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_neural_net_training_tests.test_dnn_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/duygualtinok/openface/tests/openface_neural_net_training_tests.py", line 36, in test_dnn_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

----------------------------------------------------------------------
Ran 6 tests in 6.303s

FAILED (errors=1, failures=5)
```

Then I made

```
duygualtinok@duygualtinok:~/openface$ ./util/profile-network.lua
/home/duygualtinok/torch/install/bin/luajit: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: /home/duygualtinok/torch/install/share/lua/5.1/nn/test.lua:12: attempt to call field 'TestSuite' (a nil value)
stack traceback:
    [C]: in function 'error'
    .../duygualtinok/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
    ./util/profile-network.lua:7: in main chunk
    [C]: in function 'dofile'
    ...inok/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406670
```

Any help is appreciated. I have 0 idea what's going on.

**Comment by chalene** [comment]
Hi @DuyguA, I am exactly same with you. What happen to you then?

**Comment by DuyguA** [comment]
Hi @chalene ,

I made a clean setup of Torch on Ubuntu; from scratch with using luarocks. Make sure you download everything with luarocks. Then it worked.

**Comment by chalene** [comment]
@DuyguA ,
Great, I use another PC with clean Linux and setup again. Then is worked. Many thanks for you help.
