### ISSUE TITLE
run-tests.sh fails

### ISSUE THREAD

**Issue by jpiabrantes** [cmusatyalab/openface#178]
I have just installed openface:

``` python
git clone https://github.com/cmusatyalab/openface.git
cd openface
pip2 install -r requirements.txt
python2 setup.py install
```

And I tried to run the tests by doing `sh run_tests.sh` and I get a bunch of errors:

``` sh
Failure: ImportError (No module named cv2) ... ERROR
Failure: ImportError (No module named cv2) ... ERROR
Failure: ImportError (/usr/lib/libblas.so.3: undefined symbol: gotoblas) ... ERROR
tests.openface_demo_tests.test_compare_demo ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... FAIL
Failure: ImportError (/usr/lib/libblas.so.3: undefined symbol: gotoblas) ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named cv2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/joao/github/openface/openface/__init__.py", line 3, in <module>
    from .align_dlib import AlignDlib
  File "/home/joao/github/openface/openface/align_dlib.py", line 17, in <module>
    import cv2
ImportError: No module named cv2

======================================================================
ERROR: Failure: ImportError (No module named cv2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/joao/github/openface/tests/openface_api_tests.py", line 18, in <module>
    import cv2
ImportError: No module named cv2

======================================================================
ERROR: Failure: ImportError (/usr/lib/libblas.so.3: undefined symbol: gotoblas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/joao/github/openface/tests/openface_batch_represent_tests.py", line 22, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /usr/lib/libblas.so.3: undefined symbol: gotoblas

======================================================================
ERROR: Failure: ImportError (/usr/lib/libblas.so.3: undefined symbol: gotoblas)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/joao/github/openface/tests/openface_neural_net_training_tests.py", line 21, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /usr/lib/libblas.so.3: undefined symbol: gotoblas

======================================================================
FAIL: tests.openface_demo_tests.test_compare_demo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/joao/github/openface/tests/openface_demo_tests.py", line 38, in test_compare_demo
    assert "0.763" in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

Traceback (most recent call last):
  File "/home/joao/github/openface/demos/compare.py", line 58, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/joao/github/openface/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/joao/github/openface/tests/openface_demo_tests.py", line 51, in test_classification_demo_pretrained
    assert "Predict SteveCarell with 0.97 confidence." in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

/home/joao/anaconda2/lib/python2.7/site-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
Traceback (most recent call last):
  File "/home/joao/github/openface/demos/classifier.py", line 257, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/joao/github/openface/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/joao/github/openface/tests/openface_demo_tests.py", line 55, in test_classification_demo_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

----------------------------------------------------------------------
Ran 7 tests in 1.344s

FAILED (errors=4, failures=3)
```

I have OpenCV and numpy installed and they work fine. Why am I getting these errors?

I am using Ubuntu 16.04
OpenCV 3.0.0
Numpy 1.11.1

**Comment by oscarkuo** [comment]
I think you are meant to use opencv 2.4 instead of opencv 3 

checkout https://cmusatyalab.github.io/openface/setup/#by-hand

**Comment by fivejjs** [comment]
Currently, I also get the similar error.
run 6 test failed all.

**Comment by qacollective** [comment]
Is there a chance that you have Python3 present and had OpenCV installed but built into Python 3 in stead of Python 2?

Try typing:
> python2
>>>import cv2
>>>import dlib
>>>import openface

Note that 'cv2' doesn't have anything to do with the version of OpenCV (ie its still 'import cv2' even for OpenCV 3.*).

All of that has to work before you have any chance of the tests running successfully.

In any event, building an environment for OpenFace isn't simple.  Try checking out the Dockerfiles or actually using Docker:
https://github.com/cmusatyalab/openface/blob/master/opencv-dlib-torch.Dockerfile
https://github.com/cmusatyalab/openface/blob/master/Dockerfile

**Comment by bamos** [comment]
Thanks @qacollective! Sorry I missed this thread from last August. I'm closing this issue, but anybody feel free to follow up if you're having issues running our tests.

-Brandon.
