### ISSUE TITLE
Problem with align_dlib.py

### ISSUE THREAD

**Issue by saintnik2015** [cmusatyalab/openface#184]
After installing "by hand" I've tried to run run-tests.sh and got this:

```
Failure: ArgumentError (Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)) ... ERROR
tests.openface_batch_represent_tests.test_batch_represent ... FAIL
tests.openface_demo_tests.test_compare_demo ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... FAIL
tests.openface_neural_net_training_tests.test_dnn_training ... FAIL

======================================================================
ERROR: Failure: ArgumentError (Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/saintnik/openface/tests/openface_api_tests.py", line 42, in <module>
    align = openface.AlignDlib(dlibFacePredictor)
  File "/home/saintnik/openface/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)

======================================================================
FAIL: tests.openface_batch_represent_tests.test_batch_represent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/saintnik/openface/tests/openface_batch_represent_tests.py", line 39, in test_batch_represent
    lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_demo_tests.test_compare_demo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/saintnik/openface/tests/openface_demo_tests.py", line 38, in test_compare_demo
    assert "0.763" in out
AssertionError:
-------------------- >> begin captured stdout << ---------------------

Traceback (most recent call last):
  File "/home/saintnik/openface/demos/compare.py", line 58, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/saintnik/anaconda2/lib/python2.7/site-packages/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/saintnik/openface/tests/openface_demo_tests.py", line 51, in test_classification_demo_pretrained
    assert "Predict SteveCarell with 0.97 confidence." in out
AssertionError:
-------------------- >> begin captured stdout << ---------------------

/home/saintnik/.local/lib/python2.7/site-packages/sklearn/lda.py:4: DeprecationWarning: lda.LDA has been moved to discriminant_analysis.LinearDiscriminantAnalysis in 0.17 and will be removed in 0.19
  "in 0.17 and will be removed in 0.19", DeprecationWarning)
Traceback (most recent call last):
  File "/home/saintnik/openface/demos/classifier.py", line 257, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/saintnik/anaconda2/lib/python2.7/site-packages/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/saintnik/openface/tests/openface_demo_tests.py", line 55, in test_classification_demo_training
    assert os.path.isdir(lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_neural_net_training_tests.test_dnn_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/saintnik/.local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/saintnik/openface/tests/openface_neural_net_training_tests.py", line 37, in test_dnn_training
    lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

----------------------------------------------------------------------
Ran 6 tests in 1.525s

FAILED (errors=1, failures=5)
```

OS: ubuntu 16
OpenCV version:
```
>>> cv2.__version__
'2.4.10'
```
CPU architecture: Intel
GPU architecture: Nvidia

**Comment by bamos** [comment]
Hi, I think two issues are causing this:

1. Improper dlib Python installation: Make sure their Python tests pass.
2. You need to download some data with the `./data/download-lfw-subset.sh` script

-Brandon.

**Comment by Mikebarson** [comment]
how would you download  from ./data/download-lfw-subset.sh? It's giving me a syntax error:

cd "$(dirname "$0")"

**Comment by bamos** [comment]
@Mikebarson - how are you executing the script? What bash version are you using? That should not be a syntax error. You can safely comment that line out if your working directory is `<openface>/data`, but something else might not work in your setup if that line's not working.

**Comment by Mikebarson** [comment]
@bamos  I tried using python ./data/download-lfw-subset.sh...which caused the syntax error

I then tried just doing ./data/download-lfw-subset.sh which gave me an error saying I needed to install wget which unfortunately provides nothing available for macSierra

**Comment by bamos** [comment]
@Mikebarson - right, that's not valid Python syntax. The script's written in bash and can be run with `bash [..].sh` or by using `./[..].sh`, which looks at the hashbang in the top line of the file saying to use bash.

You can install wget with homebrew or macports.

**Comment by Mikebarson** [comment]
@bamos Alright...Is wget available for macSierra?

**Comment by Mikebarson** [comment]
@bamos Okay so I was able to install wget and download the download-ifl-subset.sh. The problem now is this..Unable to open /Users/name/Downloads/openface-master/util/../models/dlib/shape_predictor_68_face_landmarks.dat

I looked at the directory and I was not able to find shape_predictor_68_face_landmarks.dat. How to fix this?

**Comment by bamos** [comment]
@Mikebarson - see our setup docs: http://cmusatyalab.github.io/openface/setup/. I recommend our Docker container to overcome most setup issues (OpenCV, dlib, and Torch can be a little tricky when installing them for the first time)

**Comment by Mikebarson** [comment]
@bamos Yes I did try the docker container. Would this work if I used it for an API?
