### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by MU001999** [cmusatyalab/openface#246]
The following error occurred when I run sphere.py , how can I make it solved ?

```
Traceback (most recent call last):
  File "demos/sphere.py", line 180, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/mu00/openface/openface/align_dlib.py", line 90, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
Boost.Python.ArgumentError: Python argument types in
    shape_predictor.__init__(shape_predictor, str)
did not match C++ signature:
    __init__(boost::python::api::object, std::string)
    __init__(_object*)
```

@pschanely @jaharkes @heman4t @bamos

**Comment by bamos** [comment]
This looks like a dlib installation issue. I recommend using our Docker container to work around this.
