### ISSUE TITLE
Unable to run the docker demo

### ISSUE THREAD

**Issue by bhanuc** [cmusatyalab/openface#261]
Hi,
I am trying to run the docker image but was unable to do so on ubuntu 16.04.
Initial error when I run `./demos/web/start-servers.sh` I get error 
```
Traceback (most recent call last):
  File "./demos/web/websocket-server.py", line 28, in <module>
    from twisted.internet.ssl import DefaultOpenSSLContextFactory
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL
ImportError: No module named OpenSSL`
So I tried by fixing it by using the following commands after few retries to get this error resolved.
`
apt-get update --fix-missing
apt-get install libssl-dev
apt-get install libffi-dev
apt-get install python-openssl
pip2 install appdirs
pip2 install pyOpenSSL
pip2 install cryptography
pip2 install service_identity
```
But now am getting error : 
```
2017-04-29 16:10:08+0000 [-] Log opened.
2017-04-29 16:10:08+0000 [-] Traceback (most recent call last):
2017-04-29 16:10:08+0000 [-]   File "./demos/web/websocket-server.py", line 371, in <module>
2017-04-29 16:10:08+0000 [-]     task.react(main)
2017-04-29 16:10:08+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/task.py", line 882, in react
2017-04-29 16:10:08+0000 [-]     finished = main(_reactor, *argv)
2017-04-29 16:10:08+0000 [-]   File "./demos/web/websocket-server.py", line 366, in main
2017-04-29 16:10:08+0000 [-]     ctx_factory = DefaultOpenSSLContextFactory(tls_key, tls_crt)
2017-04-29 16:10:08+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 104, in __init__
2017-04-29 16:10:08+0000 [-]     self.cacheContext()
2017-04-29 16:10:08+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 113, in cacheContext
2017-04-29 16:10:08+0000 [-]     ctx.use_certificate_file(self.certificateFileName)
2017-04-29 16:10:08+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 740, in use_certificate_file
2017-04-29 16:10:08+0000 [-]     _raise_current_error()
2017-04-29 16:10:08+0000 [-]   File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
2017-04-29 16:10:08+0000 [-]     raise exception_type(errors)
2017-04-29 16:10:08+0000 [-] OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]
```
Would appreciate if someone can help me figure out how to fix/mitigate this error.

**Comment by bamos** [comment]
Hi, can you run `demos/web/create-cert.sh` to create the TLS key/cert if you haven't already? I just merged in @montag's PR #260 adding TLS. I'd be happy to merge in another PR improving the docs and the error message so that this is clearer for users in the future.

-Brandon.

**Comment by montag** [comment]
It looks like it's failing on openssl. Installing openssl should fix this error.  On ubuntu that would be:

sudo apt-get install openssl

If that solves it, I can add openssl to the install-deps scripts.

**Comment by amine-benselim** [comment]
i have got the same issues running the docker container on windows 8.1 

    Traceback (most recent call last):

      File "./demos/web/websocket-server.py", line 28, in <module>
    from twisted.internet.ssl import DefaultOpenSSLContextFactory

      File "/usr/local/lib/python2.7/dist-packages/twisted/internet/ssl.py", line 59, in <module>
    from OpenSSL import SSL

    ImportError: No module named OpenSSL

although i already have openSSL installed.

**Comment by bamos** [comment]
I think we should:

1. Make the TLS in the web demo optional by modifying PR #260 so users won't have to deal with this dependency issue if they are fine running the non-secure version. By default, it should run the secure version if certs and OpenSSL is found, otherwise it should run the non-secure version and print a message about the secure version.
2. Update the Docker image so that the web demo works by default with TLS.

I'm not actively working on OpenFace, but if somebody wants to add them, I'll merge in PRs and update the Docker image.

**Comment by montag** [comment]
The easier way (rather than supporting multiple endpoints for each server) would be to simply generate certs that last 10 years and commit those. Then users would not need to generate them at all. I can make that change if it sounds reasonable.
