### ISSUE TITLE
Error during evaluation

### ISSUE THREAD

**Issue by akshay-vaidya** [cmusatyalab/openface#291]
While testing the pretrained model, I am getting the below error,
Traceback (most recent call last):
  File "./lfw.py", line 315, in <module>
    main()
  File "./lfw.py", line 76, in main
    verifyExp(args.workDir, pairs, embeddings)
  File "./lfw.py", line 199, in verifyExp
    writeROC(fname, thresholds, embeddings, pairs[test])
  File "./lfw.py", line 116, in writeROC
    (x1, x2, actual_same) = getEmbeddings(pair, embeddings)
  File "./lfw.py", line 105, in getEmbeddings
    (x1, x2) = (embeddings[name1], embeddings[name2])
KeyError: 'Akhmed_Zakayev_0001'

I am testing testing the model using just 1 image. KIndly help to fix this issue.

**Comment by ramanjotkaur90** [comment]
This issue still exists
