### ISSUE TITLE
 error "/usr/bin/env: th: No such file or directory" 

### ISSUE THREAD

**Issue by linengmiao** [cmusatyalab/openface#293]
Hello

I think my issue is very straightforward. I am trying to get the openface library to work on my ubuntu 16.04 machine. I am following [those steps ](https://cmusatyalab.github.io/openface/setup/)in order to install everytthing and all the depencencies. I installed successfully Torch. I can now use the Torch virtual environment by typing 'th' in my terminal. However when trying to run the  run-tests.sh script I get a message complaining about the fact that there is no th file or directory. How can I solve this issue? 

Below the generated output:
```

:~/openface$ ./run-tests.sh 
/usr/bin/env: ‘th’: No such file or directory
tests.openface_api_tests.test_pipeline ... FAIL
tests.openface_batch_represent_tests.test_batch_represent ... FAIL
tests.openface_demo_tests.test_compare_demo ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained ... FAIL
tests.openface_demo_tests.test_classification_demo_pretrained_multi ... FAIL
tests.openface_demo_tests.test_classification_demo_training ... FAIL
tests.openface_neural_net_training_tests.test_dnn_training ... FAIL

======================================================================
FAIL: tests.openface_api_tests.test_pipeline
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_api_tests.py", line 57, in test_pipeline
    assert bb.left() == 341
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
Bounding box found was: 
[(354, 206) (1019, 872)]

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_batch_represent_tests.test_batch_represent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_batch_represent_tests.py", line 40, in test_batch_represent
    lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_demo_tests.test_compare_demo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_demo_tests.py", line 39, in test_compare_demo
    assert '0.763' in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

Traceback (most recent call last):
  File "/home/yalishanda/openface/demos/compare.py", line 33, in <module>
    import openface
ImportError: No module named openface


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_demo_tests.py", line 52, in test_classification_demo_pretrained
    assert 'Predict SteveCarell with 0.97 confidence.' in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

Traceback (most recent call last):
  File "/home/yalishanda/openface/demos/classifier.py", line 37, in <module>
    import openface
ImportError: No module named openface


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_pretrained_multi
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_demo_tests.py", line 65, in test_classification_demo_pretrained_multi
    assert 'Predict EvaLongoria @ x=91 with 0.99 confidence.' in out
AssertionError: 
-------------------- >> begin captured stdout << ---------------------

Traceback (most recent call last):
  File "/home/yalishanda/openface/demos/classifier.py", line 37, in <module>
    import openface
ImportError: No module named openface


--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: tests.openface_demo_tests.test_classification_demo_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_demo_tests.py", line 70, in test_classification_demo_training
    assert os.path.isdir(lfwSubset), 'Get lfw-subset by running ./data/download-lfw-subset.sh'
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

======================================================================
FAIL: tests.openface_neural_net_training_tests.test_dnn_training
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yalishanda/openface/tests/openface_neural_net_training_tests.py", line 38, in test_dnn_training
    lfwSubset), "Get lfw-subset by running ./data/download-lfw-subset.sh"
AssertionError: Get lfw-subset by running ./data/download-lfw-subset.sh

----------------------------------------------------------------------
Ran 7 tests in 7.153s

FAILED (failures=7)

```

**Comment by linengmiao** [comment]
simply restarted my laptop and the issue got solved...
