### ISSUE TITLE
Calling net.forward(alignedFace), Error getting result from Torch subprocess

### ISSUE THREAD

**Issue by MahmoudSrour** [cmusatyalab/openface#316]
### Context of the issue.
`INFO 2017-10-16 12:05:10,191 face_compare.py 47: End getting Largest Face Bounding Box
INFO 2017-10-16 12:05:10,191 face_compare.py 52: Face detection took 8.63339614868 seconds.
INFO 2017-10-16 12:05:10,195 face_compare.py 61: Face alignment took 0.00392603874207 seconds.
/root/torch/install/bin/luajit: inconsistent tensor size at /root/torch/pkg/torch/lib/TH/generic/THTensorCopy.c:7
stack traceback:
	[C]: at 0x7ff8239e5210
	[C]: in function '__newindex'
	...lib/python2.7/dist-packages/openface/openface_server.lua:64: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

Error getting result from Torch subprocess.

Line read: 

Exception:

could not convert string to float: 

============

stdout: 

----------------------------------------
Exception happened during processing of request from ('172.17.0.1', 46612)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 232, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 267, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 197, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/src/app.py", line 57, in compare
    distance = face_compare.compare(img1, img2)
  File "/src/face_compare.py", line 38, in compare
    d = self.getRep(rgbImg1) - self.getRep(rgbImg2)
  File "/src/face_compare.py", line 64, in getRep
    rep = self.net.forward(alignedFace)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 204, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python2.7/dist-packages/openface/torch_neural_net.py", line 187, in forwardPath
    sys.exit(-1)
SystemExit: -1
`

### Expected behavior.
[Describe what you would expect to have resulted from this process.]

### Actual behavior.
[Describe what you currently experience from this process, and thereby explain the bug.]

### Steps to reproduce.
[Present a minimal example and steps to produce the issue.]

### OS and hardware information.

+ Operating system: ubutnu 17.04
+ Torch version: Torch7

**Comment by MahmoudSrour** [comment]
@bamos please advise if there is a solution for that issue

also, Please let me if you needs more details.

**Comment by sharatss** [comment]
Can anyone please tell how this issue was solved? I am facing the same issue

**Comment by xugaoxiang** [comment]
me too.
