### ISSUE TITLE
Unable to run openface demo

### ISSUE THREAD

**Issue by chasad** [cmusatyalab/openface#327]
Trying to run openface demo but unable to access the camera and Local servers status is disconnected. Terminal output is as under
2017-11-29 13:46:12-0500 [-] Log opened.
2017-11-29 13:46:12-0500 [-] WebSocketServerFactory starting on 9000
2017-11-29 13:46:12-0500 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7fc6eb26eb90>
2017-11-29 13:46:21-0500 [-] Client connecting: tcp4:127.0.0.1:43786
2017-11-29 13:46:21-0500 [-] server state: []
2017-11-29 13:46:21-0500 [-] WebSocket connection open.
2017-11-29 13:46:21-0500 [-] loading state... []
2017-11-29 13:46:21-0500 [-] + Training SVM on 0 labeled images.
2017-11-29 13:46:21-0500 [OpenFaceServerProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
	    return self._dataReceived(data)
	  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 101, in dataReceived
	    self._dataReceived(data)
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1299, in _dataReceived
	    self.consumeData()
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1314, in consumeData
	    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1466, in processData
	    return self.processDataHybi()
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1777, in processDataHybi
	    fr = self.onFrameEnd()
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1904, in onFrameEnd
	    self._onMessageEnd()
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 129, in _onMessageEnd
	    self.onMessageEnd()
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 731, in onMessageEnd
	    self._onMessage(payload, self.message_is_binary)
	  File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 132, in _onMessage
	    self.onMessage(payload, isBinary)
	  File "./cloudlet-demo-openface-server.py", line 172, in onMessage
	    resp=self.processFrame(msg['dataURL'], msg['name'])
	exceptions.KeyError: 'name'
	
2017-11-29 13:46:21-0500 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)

Accessing it from Google chrome
![screenshot from 2017-11-29 13 50 05](https://user-images.githubusercontent.com/12442995/33393480-4d5b79c6-d50d-11e7-829d-639f231c819d.png)

**Comment by fungtion** [comment]
I have the same problem

**Comment by rvpisal** [comment]
@fungtion .... How did you change the mapping and access over 8000...?? Can you please let me know the steps..?? I am using ubuntu 17.10 and experiencing the same issue

**Comment by fungtion** [comment]
@rvpisal simply replace the original port with 8000 in html and js files

**Comment by rvpisal** [comment]
@fungtion Still the same error... I changed ports from 9000 to 8000 in "websocket-server.py file", and "openface-demo.js" in "https://github.com/cowbjt/openface/tree/demo-web-stand-alone" code.


Error:

2018-02-26 16:34:36-0600 [OpenFaceServerProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/python/log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
	    why = selectable.doRead()
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 209, in doRead
	    return self._dataReceived(data)
	  File "/home/rohan/.local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 215, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 101, in dataReceived
	    self._dataReceived(data)
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1299, in _dataReceived
	    self.consumeData()
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1314, in consumeData
	    while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1466, in processData
	    return self.processDataHybi()
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1777, in processDataHybi
	    fr = self.onFrameEnd()
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 1904, in onFrameEnd
	    self._onMessageEnd()
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 129, in _onMessageEnd
	    self.onMessageEnd()
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/websocket/protocol.py", line 731, in onMessageEnd
	    self._onMessage(payload, self.message_is_binary)
	  File "/home/rohan/.local/lib/python2.7/site-packages/autobahn/twisted/websocket.py", line 132, in _onMessage
	    self.onMessage(payload, isBinary)
	  File "./demos/web/websocket-server.py", line 175, in onMessage
	    self.trainingFrame(msg['dataURL'], msg['identity'])
	  File "./demos/web/websocket-server.py", line 321, in trainingFrame
	    name = self.people[identity]
	exceptions.IndexError: list index out of range

**Comment by fungtion** [comment]
@rvpisal it reminds that something wrong with **name = self.people[identity]**, identity is the index of the people, you can check this  error in websocket-server.py.

**Comment by rvpisal** [comment]
@fungtion Yup... I know something is wrong with "identity"... but do you recollect what it reminds you of..?? This error only pops up when I turn on the training mode....

**Comment by fungtion** [comment]
@rvpisal you can create a new txt file in websocket-server.py and save the identity value in it.

**Comment by rvpisal** [comment]
@fungtion ....Thank you for your help... Now it's running fine... Just the problem is not the image data is not entering the database. However, it is not giving any error... Can you suggest something..??

**Comment by fungtion** [comment]
@rvpisal you can debug function `processFrame` to check if your image was read.
