### ISSUE TITLE
IOError:  File comparisons/openbr.v1.1.0.DET.csv does not exist?

### ISSUE THREAD

**Issue by irving2** [cmusatyalab/openface#360]
after I have run all the Epochs over， this error raised:

Traceback (most recent call last):
  File "../evaluation/lfw.py", line 313, in <module>
    main()
  File "../evaluation/lfw.py", line 77, in main
    plotVerifyExp(args.workDir, args.tag)
  File "../evaluation/lfw.py", line 259, in plotVerifyExp
    openbrData = pd.read_csv("comparisons/openbr.v1.1.0.DET.csv")
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File comparisons/openbr.v1.1.0.DET.csv does not exist

but, I have checked that   the CSV file in comparisons/openbr.v1.1.0.DET.csv does exitsted!
it's very perciated to receive your sugguestions,thanks!

**Comment by taureanamir** [comment]
@irving2 , @bamos 
I too encounter this issue while running evaluation. The file exists but the process is not able to find the file.
