### ISSUE TITLE
Error in using demos/compare.py- 'TorchNeuralNet' object has no attribute 'p' 

### ISSUE THREAD

**Issue by mrazimi** [cmusatyalab/openface#376]
Traceback (most recent call last):
  ```
File "compare.py", line 59, in <module>
    net = openface.TorchNeuralNet(args.networkModel, args.imgDim)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\openface\torch_neural_net.py", line 84, in __init__
    self.p = Popen(self.cmd, stdin=PIPE, stdout=PIPE, bufsize=0, universal_newlines=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku
Exception ignored in: <bound method TorchNeuralNet.__del__ of <openface.torch_neural_net.TorchNeuralNet object at 0x0000021F364A1160>>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\site-packages\openface\torch_neural_net.py", line 109, in __del__
    if self.p.poll() is None:
AttributeError: 'TorchNeuralNet' object has no attribute 'p'
```

**Comment by magicshuang** [comment]
这就不是给Windows用的
![image](https://user-images.githubusercontent.com/36405349/60569254-73d2c880-9da1-11e9-8e22-9c22aae96dce.png)

**Comment by tap222** [comment]
@magicshuang , I am getting the same error. can you please let me know how to fix it for windows.

**Comment by mjan2021** [comment]
Hi, 
I am having same issue in windows. I already installed on MacOS and it working there which make sense as this is for Unix Based, but how can this be achieved on a windows pc?

thank you
