### ISSUE TITLE
Can't establish a connection to the server, Web Demo, Docker

### ISSUE THREAD

**Issue by JannisBush** [cmusatyalab/openface#378]
### Context of the issue.
I installed the docker version of openface and tried to run the web demo there. But when I'm on the website, I can't connect to the server and therefore the application does not work.
The other examples work.

### Expected behavior.
The web demo works, i.e. displays the video of my webcam.

### Actual behavior.
I can load the website, but can't connect to the local server.
![image](https://user-images.githubusercontent.com/33023300/43958019-d72df6c2-9ca1-11e8-90c1-b38ade0c1953.png)

### Steps to reproduce.
`$ docker run -p 9000:9000 -p 8000:8000 -t -i bamos/openface /bin/bash`
`# cd root/openface/`
`# demos/web/start-server.sh`
Then find out the docker ip (`docker inspect <docker_ip> | grep IPAddress`), open a web browser and connect to the website `https://<docker-ip>:8000`. Accept the certificate and allow access to the camera. Now, I am connected to the website, but the local server is disconnected. 

### OS and hardware information.

+ Operating system: Ubuntu 16.04 Desktop 64bit
+ Torch version: ?
+ CPU architecture: core i7
+ GPU type (if using): None

### Content of `/tmp/openface.websocket.log` 
```
2018-08-10 12:02:33+0000 [-] Log opened.  
2018-08-10 12:02:33+0000 [-] WebSocketServerFactory (TLS) starting on 9000  
2018-08-10 12:02:33+0000 [-] Starting factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f810dc6c390>  
2018-08-10 12:02:38+0000 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)  
2018-08-10 12:07:38+0000 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)  
2018-08-10 12:17:41+0000 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)  
2018-08-10 12:21:18+0000 [-] Received SIGTERM, shutting down.  
2018-08-10 12:21:18+0000 [twisted.protocols.tls.TLSMemoryBIOFactory] (TLS Port 9000 Closed)  
2018-08-10 12:21:18+0000 [twisted.protocols.tls.TLSMemoryBIOFactory] Stopping factory <autobahn.twisted.websocket.WebSocketServerFactory object at 0x7f810dc6c390>  
2018-08-10 12:21:18+0000 [-] Main loop terminated.
```

One `WebSocket connection closed` for every page reload I did, then I stopped the script with `ctrl-c`.

### Content of Browsers Developer Console
```
Firefox can’t establish a connection to the server at wss://172.17.0.2:9000/. openface-demo.js:157:13
Error creating WebSocket connection to wss://172.17.0.2:9000 openface-demo.js:225:9
error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 310, cancelBubble: false, … }
openface-demo.js:226:9
Firefox can’t establish a connection to the server at wss://172.17.0.2:9000/. openface-demo.js:157:13
Error creating WebSocket connection to wss:172.17.0.2:9000 openface-demo.js:225:9
error { target: WebSocket, isTrusted: true, currentTarget: WebSocket, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 603571, cancelBubble: false, … }
openface-demo.js:226:9
```

### What I tried to resolve the problem
I tried going back to the http version using this #302 suggestion. This worked, but then I faced another problem, namely the camera screen was black as in #319 .

How can I make the web demo work, either with a correct connection to the wss-server or without the blackscreen using the ws-server?

**Comment by JannisBush** [comment]
I just tried running it with `chromium` and there it works.
Maybe adding a warning somewhere that it does not work with `firefox` would be nice (or was there one, I have not seen?) .
