### ISSUE TITLE
compare demo does not work

### ISSUE THREAD

**Issue by guitar9** [cmusatyalab/openface#385]
I did the installation steps

get this error:

```
/usr/bin/env: »th“: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "./demos/compare.py", line 101, in <module>
    d = getRep(img1) - getRep(img2)
  File "./demos/compare.py", line 92, in getRep
    rep = net.forward(alignedFace)
  File "/home/t/openface/openface/torch_neural_net.py", line 204, in forward
    rep = self.forwardPath(t)
  File "/home/t/openface/openface/torch_neural_net.py", line 161, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception: 


OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Advanced Users: If you think this problem is caused by
running Lua as a subprocess, Vitalius Parubochyi has created
a version of this that uses https://github.com/imodpasteur/lutorpy.
This file is available at <openface>/openface/torch_neural_net.lutorpy.py
and our mailing list discussion on this can be found at:
https://groups.google.com/forum/#!topic/cmu-openface/Jj68LJBdN-Y

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/home/t/openface/openface/openface_server.lua', '-model', '/home/t/openface/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout: 

```

### OS and hardware information.
+ Operating system: [Linux]

**Comment by omerasif57** [comment]
Any pointer for this solution?
