### ISSUE TITLE
Error run openface python3 compare.py

### ISSUE THREAD

**Issue by blinkbink** [cmusatyalab/openface#406]
### Context of the issue.
Ii try run compare.py, `python3 compare.py {1*, 2*}`

### Expected behavior.
I want to see score compare from 2 image

### Actual behavior.
but i got this error:

```
Traceback (most recent call last):
  File "compare.py", line 102, in <module>
    d = getRep(img1) - getRep(img2)
  File "compare.py", line 93, in getRep
    rep = net.forward(alignedFace)
  File "/usr/local/lib/python3.6/dist-packages/openface/torch_neural_net.py", line 204, in forward
    rep = self.forwardPath(t)
  File "/usr/local/lib/python3.6/dist-packages/openface/torch_neural_net.py", line 161, in forwardPath
    """.format(self.cmd, self.p.stdout.read()))
Exception:

OpenFace: `openface_server.lua` subprocess has died.

+ Is the Torch command `th` on your PATH? Check with `which th`.

+ If `th` is on your PATH, try running `./util/profile-network.lua`
  to see if Torch can correctly load and run the network.

  + If this gives illegal instruction errors, see the section on
    this in our FAQ at http://cmusatyalab.github.io/openface/faq/

  + In Docker, use a Bash login shell or source
     /root/torch/install/bin/torch-activate for the Torch environment.

+ See this GitHub issue if you are running on a non-64-bit machine:
  https://github.com/cmusatyalab/openface/issues/42

+ Advanced Users: If you think this problem is caused by
running Lua as a subprocess, Vitalius Parubochyi has created
a version of this that uses https://github.com/imodpasteur/lutorpy.
This file is available at <openface>/openface/torch_neural_net.lutorpy.py
and our mailing list discussion on this can be found at:
https://groups.google.com/forum/#!topic/cmu-openface/Jj68LJBdN-Y

+ Please post further issues to our mailing list at
  https://groups.google.com/forum/#!forum/cmu-openface

Diagnostic information:

cmd: ['/usr/bin/env', 'th', '/usr/local/lib/python3.6/dist-packages/openface/openface_server.lua', '-model', '/tmp/openface-master/demos/../models/openface/nn4.small2.v1.t7', '-imgDim', '96']

============

stdout:
```
any advices ?

### OS and hardware information.

+ Operating system: Ubuntu 18.04
+ Torch version: 1.0
+ CPU architecture: 64
+ GPU type (if using): Nvidia Tesla V100 32Gb

**Comment by 705062791** [comment]
hi, i was stuck in this problem as you, have you already solved this problem?
