### ISSUE TITLE
Web Demo: Cannot connect camera in Chrome on Windows, works on Firefox

### ISSUE THREAD

**Issue by ariestar** [cmusatyalab/openface#59]
Hi,

I've tried to experiment with the Web Demo and although I can follow all the steps and "Demo 2 comparison" works fine, the web demo is having some issues.
I was able to download and install all the dependencies, I start the server and then the SimpleHTTPServer for the file. All is correctly bound and forwarded and I am using two machines.

Here is what I get from the console. I have both processes outputting in the same view:

192.168.1.106 - - [24/Nov/2015 08:35:27] "GET / HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/css/bootstrap.min.css HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/css/bootstrap-toggle.min.css HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/css/bootstrap-dialog.min.css HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/js/jquery.min.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /css/main.css HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/js/bootstrap.min.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/js/bootstrap-dialog.min.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /js/utils.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/js/handlebars.min.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /vendor/js/jstat.min.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:27] "GET /js/openface-demo.js HTTP/1.1" 200 -
192.168.1.106 - - [24/Nov/2015 08:35:28] "GET /vendor/js/bootstrap-toggle.min.js HTTP/1.1" 200 -
2015-11-24 08:35:28+0000 [-] Client connecting: tcp4:192.168.1.106:65033
2015-11-24 08:35:28+0000 [-] WebSocket connection open.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received NULL message of length 15.
2015-11-24 08:35:28+0000 [-] Received ALL_STATE message of length 61.
2015-11-24 08:35:28+0000 [-] + Training SVM on 0 labeled images.
2015-11-24 08:35:31+0000 [-] Received FRAME message of length 3438.
2015-11-24 08:35:32+0000 [-] Received FRAME message of length 3438.
2015-11-24 08:35:32+0000 [-] Received FRAME message of length 11810.
2015-11-24 08:35:33+0000 [OpenFaceServerProtocol,6,192.168.1.106] Unhandled Error
        Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 611, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 209, in doRead
            return self._dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 215, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 101, in dataReceived
            self._dataReceived(data)
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1299, in _dataReceived
            self.consumeData()
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1314, in consumeData
            while self.processData() and self.state != WebSocketProtocol.STATE_CLOSED:
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1466, in processData
            return self.processDataHybi()
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1777, in processDataHybi
            fr = self.onFrameEnd()
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 1904, in onFrameEnd
            self._onMessageEnd()
          File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 129, in _onMessageEnd
            self.onMessageEnd()
          File "/usr/local/lib/python2.7/dist-packages/autobahn/websocket/protocol.py", line 731, in onMessageEnd
            self._onMessage(payload, self.message_is_binary)
          File "/usr/local/lib/python2.7/dist-packages/autobahn/twisted/websocket.py", line 132, in _onMessage
            self.onMessage(payload, isBinary)
          File "./server.py", line 123, in onMessage
            self.processFrame(msg['dataURL'], msg['identity'])
          File "./server.py", line 287, in processFrame
            rep = net.forwardImage(alignedFace)
          File "/openface/openface/demos/web/../../openface/__init__.py", line 105, in forwardImage
            rep = np.array(self.forwardPath(t))
          File "/openface/openface/demos/web/../../openface/__init__.py", line 69, in forwardPath
            """.format(self.cmd, self.p.stdout.read(), self.p.stderr.read()))
        exceptions.ValueError: I/O operation on closed file

2015-11-24 08:35:33+0000 [-] WebSocket connection closed: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)

Is there anything really simple I'm missing on this?

Thanks a lot for your help with this..

**Comment by bamos** [comment]
Hi @ariestar - nothing stands out to me in the server log. Can you check for an any errors in Chrome's developer console?

**Comment by ariestar** [comment]
Hi @bamos, thanks for the tip, at least now I know why Chrome doesn't work at all:
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

I'll try the Firefox console as well as that one generated all the above errors.

Thanks for your quick reply on these.

**Comment by ariestar** [comment]
Hi again @bamos,

Here's what I get in Firefox's console. It doesn't complain about the user permissions, goes ahead any listens on the socket and then it crashes:

message { target: WebSocket, isTrusted: true, data: "{"type": "NULL"}", origin: "ws://192.168.1.145:9000", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1448367967299000, originalTarget: WebSocket } openface-demo.js:168:8
message { target: WebSocket, isTrusted: true, data: "{"identities": [], "type": "IDENTITIES"}", origin: "ws://192.168.1.145:9000", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1448367970602000, originalTarget: WebSocket } openface-demo.js:168:8
message { target: WebSocket, isTrusted: true, data: "{"content": "data:image/png;base64,<base64 of my webcam data was replaced>", "type": "ANNOTATED"}", origin: "ws://192.168.1.145:9000", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1448367970603000, originalTarget: WebSocket } openface-demo.js:168:8
message { target: WebSocket, isTrusted: true, data: "{"type": "PROCESSED"}", origin: "ws://192.168.1.145:9000", lastEventId: "", eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1448367970604000, originalTarget: WebSocket }

**Comment by ariestar** [comment]
![image](https://cloud.githubusercontent.com/assets/2768779/11366761/4a3069d2-92a7-11e5-9711-0ca51813d6ba.png)
And without any training data, I think basically it's checking the person once and then crashes.. It's not looping probably, I'm open for advice..

**Comment by bamos** [comment]
@ariestar - can you try pulling the latest code from the master branch? I think I've added more debug information so the trace in the server log will be more informative. Also are you able to run the comparison demo?

**Comment by berli** [comment]
@bamos  this issue is very common, I have also the issue

**Comment by bamos** [comment]
Closing due to inactivity.
