### ISSUE TITLE
openface web

### ISSUE THREAD

**Issue by kartx22** [cmusatyalab/openface#74]
hi i got this error while starting the server 

kartx22:~/workspace (master) $ ./demos/web/start-servers.sh
HTTP Port: 8000
WebSocket Port: 9000

WebSocket Server: Logging to '/tmp/openface.websocket.log'

libdc1394 error: Failed to initialize libdc1394
Traceback (most recent call last):
  File "./demos/web/websocket-server.py", line 52, in <module>
    from openface.alignment import NaiveDlib  # Depends on dlib.
  File "/home/ubuntu/workspace/demos/web/../../openface/alignment/__init__.py", line 3, in <module>
    from .naive_dlib import NaiveDlib
  File "/home/ubuntu/workspace/demos/web/../../openface/alignment/naive_dlib.py", line 16, in <module>
    import dlib
ImportError: No module named dlib

**Comment by bamos** [comment]
HI @kartx22 - I just posted an announcement to our mailing list addressing this at https://groups.google.com/forum/#!topic/cmu-openface/s3gtNEKtmaw.
I'm closing this issue, but please respond on the mailing list post if the fix doesn't work.

-Brandon.
