### ISSUE TITLE
demo1:RuntimeError

### ISSUE THREAD

**Issue by shakevincent** [cmusatyalab/openface#76]
hello.I am alread success run the demo2.But when I run the demo1.the error is
Traceback (most recent call last):
  File "./demos/web/websocket-server.py", line 72, in <module>
    align = openface.AlignDlib(args.dlibFacePredictor)
  File "/home/lyz/openface-master/demos/web/../../openface/align_dlib.py", line 89, in __init__
    self.predictor = dlib.shape_predictor(facePredictor)
RuntimeError: Unable to open /home/lyz/openface-master/demos/web/../../models/dlib/shape_predictor_68_face_landmarks.dat
,who can help me! Thank you very much.

**Comment by bamos** [comment]
Hi @shakevincent - does the file `/home/lyz/openface-master/demos/web/../../models/dlib/shape_predictor_68_face_landmarks.dat` exist?

**Comment by shakevincent** [comment]
Hi @bamos i am sure the file exist.  I get the model again  the demo1 alread success.thank you very much.have a good day

**Comment by bamos** [comment]
Hi @shakevincent - I'm not sure what could be causing this because the dlib initialization code is identical between the comparison and web demos and only depends on the string to the dlib model's location on disk. The latest web demo is also working well on my OSX machine and in a Linux Docker container. This could be a setup issue or an inconsistency between our systems I've overlooked.

Can you try using the Docker version?

Can you try the following from a Python 2 interpreter?

```Python
import dlib
predictor = dlib.shape_predictor("/home/lyz/openface-master/demos/web/../../models/dlib/shape_predictor_68_face_landmarks.dat")
```

Are you running the web demo as a different user that doesn't have permissions to the dlib model file?

-Brandon.

**Comment by bamos** [comment]
Closing due to inactivity.

**Comment by deepmore1** [comment]
Hello bamos i had the same error as @shakevincent  , i'm actually doubting the opencv version i am using is incompatible with the one openface was made with i am using opencv 3.2 ,python 2.7 ,am i getting this right ?

**Comment by deepmore1** [comment]
i tried the following from a Python 2 interpreter as you previously said : 
```
import dlib
predictor = dlib.shape_predictor("/home/lyz/openface-master/demos/web/../../models/dlib/shape_predictor_68_face_landmarks.dat")
```
i get this error : RuntimeError: Unable to open /home/lyz/openface-master/demos/web/../../models/dlib/shape_predictor_68_face_landmarks.dat

**Comment by bamos** [comment]
Hi @deepmore1, does that file exist?

**Comment by deepmore1** [comment]
Hi Brandon ,
Thank for your response, i actually worked it out,the fille didn't exist
and then i reinstalled dlib's dependencies and it worked just well now i'm
reading your discussion about the unknown faces detection because it's the
most important aspect regarding the project i'm working on.
i worked before using openface on opencv with c++ for face recognition and
managed to pull out unknown person's identification with a certain
confidence value,in a way that unknown persons are never known and the
known one's recognition is a bit worse .
so how far did you achieve regarding that matter ?
Cheers

2017-04-28 13:49 GMT+01:00 Brandon Amos <notifications@github.com>:

**Comment by eacosta1976** [comment]
I have the same problem:  How did you solved it.
  I got this error:

RuntimeError: Unable to open /Users/edgaracosta/openface/openface/demos/../models/dlib/shape_predictor_68_face_landmarks.dat

I have Mac OSX Sierra

**Comment by eacosta1976** [comment]
I realize that inside.   /models/dlib/

  the   fileshape_predictor_68_face_landmarks.dat. 

  is Missing!!!!

**Comment by gaoyangyiqiao** [comment]
Met the same problem. How is this fixed?

**Comment by RohiniBridgitteStanly** [comment]
[INFO] loading facial landmark predictor...
Getting Runtime error:
Unable to open 68 face landmarks.dat

**Comment by anujnadig168** [comment]
I was facing this same problem on my Windows laptop running Python 3.6. All I did to solve this, was add the complete path location inside the single quotes even though my console directory was the same folder that consisted this file.

**Comment by Lau98GH** [comment]
@anujnadig168  Hi, I am studying _Deep learning: Face recognition_ in Lynda, and face this same problem on my Windows laptop, could you please told me how you solved it?

**Comment by DeepmindHub** [comment]
Hi I faced the same problem in macos . Unable to open /Users/ankurpal/Documents/open_cv_faces/cv4faces/common/shape_predictor_68_face_landmarks.dat 
I have given correct path where file (shape_predictor_68_face_landmarks.dat ) exist .Dlib installed properly and file exist in my case . what could be the main problem /?

**Comment by SidharthRai** [comment]
Getting a new error how to solve this?,
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by ezrabest** [comment]
Solved by changing the folder location in the .py file to the correct location of shape_predictor_68_face_landmarks.dat
alternatively you can move the shape_predictor_68_face_landmarks.dat file to the default folder

**Comment by Sixuan-Li** [comment]
@SidharthRai  Hey may I ask did you solve the problem? I am getting the same error and could not fix it.I am pretty sure the file is in the path. Thank you very much!

**Comment by siddharthmagadum16** [comment]
for my project, I placed the files in a same directory and executed the command according to my program. Those are called args (arguments).
(i use windows 10)
command.
python detect_drowsiness.py --shape_predictor shape_predictor_68_face_landmarks.dat --alarm alarm.wav --webcam 0

**Comment by programmist87** [comment]
Добрый день. Вы можете подсказать, что это за файл, shape_predictor_68_face_landmarks.dat? Появился на смартфоне. Его создаёт какое-то определённое приложение? Или его создают разные приложения?

**Comment by zhaixing** [comment]
##########This may help you##########
1.Find your api.py file path (eg.C:\Python39\Lib\site-packages\face_recognition\api.py) in your python Interpreter path.
2.Change line 21 "pose_predictor_68_point = dlib.shape_predictor(predictor_68_point_model)" to
pose_predictor_68_point = dlib.shape_predictor("shape_predictor_68_face_landmarks.dat")
3.pyinstaller you_python_file.py
4.copy "shape_predictor_68_face_landmarks.dat" to dist dir。

Note that error is in C:\Python39\Lib\site-packages\face_recognition\api.py on line 21,good luck!
